// This Source Code Form is subject to the terms of the MIT License.
// If a copy of the MIT was not distributed with this file, You can obtain one at https://opensource.org/licenses/MIT.
// Copyright (C) Barbatos Labs | Pham The Hung and Barbatos.Pallas Contributors.
// All Rights Reserved.

using System.Collections.Immutable;
using Barbatos.Pallas.Engine;
using Barbatos.Pallas.Spreadsheet;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

namespace Barbatos.Pallas.Presentation;

/// <summary>
/// The Table screen (manual pp. 107-111): f(x) and g(x) over a range of x, row by row.
/// </summary>
/// <remarks>
/// The functions are defined in the session, as they are everywhere else in the calculator, and the table is
/// generated by the Spreadsheet package; the screen holds the range and what came out. The graph
/// (<see cref="TableGraphViewModel"/>) is a second view of the same table, drawn again whenever the table changes.
/// </remarks>
public sealed partial class TableViewModel : ObservableObject
{
    private readonly CalculatorSession _session;
    private NumberTable? _table;

    /// <summary>Creates the screen over a session.</summary>
    /// <param name="session">The session the table is generated from.</param>
    /// <exception cref="ArgumentNullException"><paramref name="session"/> is <see langword="null"/>.</exception>
    public TableViewModel(CalculatorSession session)
    {
        ArgumentNullException.ThrowIfNull(session);
        _session = session;
        Range = new ValueGridViewModel(session, 1, 3);
        Range[0, 0].Text = "1";
        Range[0, 1].Text = "5";
        Range[0, 2].Text = "1";
        Graph = new TableGraphViewModel(session);
    }

    /// <summary>Gets the kinds of table there are: f(x) alone, or f(x) and g(x) (p. 107).</summary>
    public ImmutableArray<TableType> Types { get; } = [.. Enum.GetValues<TableType>()];

    /// <summary>Gets the start, the end and the step of x.</summary>
    public ValueGridViewModel Range { get; }

    /// <summary>Gets the graph of the table: its functions over its rows.</summary>
    public TableGraphViewModel Graph { get; }

    /// <summary>Gets or sets whether the screen shows the graph of the table rather than its rows.</summary>
    [ObservableProperty]
    private bool _isGraphShown;

    /// <summary>Gets or sets which functions the table holds.</summary>
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(RowLimit))]
    private TableType _type = TableType.FunctionsFAndG;

    /// <summary>Gets or sets f(x), as Canonical Linear Syntax.</summary>
    [ObservableProperty]
    private string _functionF = "x²";

    /// <summary>Gets or sets g(x), as Canonical Linear Syntax; only used when the table holds both.</summary>
    [ObservableProperty]
    private string _functionG = "x+1";

    /// <summary>Gets the rows of the table.</summary>
    [ObservableProperty]
    private ImmutableArray<TableRow> _rows = [];

    /// <summary>Gets the localization key of the error, or <see langword="null"/>.</summary>
    [ObservableProperty]
    private string? _errorKey;

    /// <summary>Gets how many rows this kind of table may have in this profile (p. 107).</summary>
    public int RowLimit => NumberTable.RowLimit(Type, _session.Profile);

    /// <summary>Defines the functions and generates the table.</summary>
    [RelayCommand]
    public void Generate()
    {
        ErrorKey = null;
        Rows = [];
        _table = null;
        Graph.Clear();

        CalcError? fault = Type is TableType.FunctionG ? null : _session.Define(DefinedFunction.F, FunctionF);
        fault ??= Type is TableType.FunctionF ? null : _session.Define(DefinedFunction.G, FunctionG);
        if (fault is { } wrong)
        {
            ErrorKey = "error." + wrong.Kind;
            return;
        }

        NumberTable table = NumberTable.Generate(_session, Type, Range[0, 0].Value, Range[0, 1].Value, Range[0, 2].Value);
        _table = table;
        ErrorKey = table.Error is { } error ? "error." + error.Kind : null;
        Rows = [.. table.Rows];
        Graph.Show(table);
    }

    /// <summary>Changes the x of one row and calculates that row again (p. 110).</summary>
    /// <param name="row">The row, counted from 0.</param>
    /// <param name="x">What x is now.</param>
    /// <returns><see langword="true"/> when there is such a row.</returns>
    public bool SetX(int row, Value x)
    {
        if (_table is not { } table || row < 0 || row >= table.Rows.Count)
        {
            return false;
        }

        table.SetX(row, x);
        Rows = [.. table.Rows];
        Graph.Show(table);
        return true;
    }

    /// <summary>Removes one row of the table (p. 110).</summary>
    /// <param name="row">The row, counted from 0.</param>
    /// <returns><see langword="true"/> when there was such a row.</returns>
    public bool RemoveRow(int row)
    {
        if (_table is not { } table || row < 0 || row >= table.Rows.Count)
        {
            return false;
        }

        table.RemoveRow(row);
        Rows = [.. table.Rows];
        Graph.Show(table);
        return true;
    }

    /// <summary>Checks an answer against what the table holds (Verify, p. 111).</summary>
    /// <param name="row">The row, counted from 0.</param>
    /// <param name="function">Which function.</param>
    /// <param name="answer">The answer to check.</param>
    /// <returns>Whether it is right, or <see langword="null"/> when there is nothing to check it against.</returns>
    public bool? Verify(int row, TableFunction function, string answer)
    {
        return _table is { } table && row >= 0 && row < table.Rows.Count ? table.Verify(row, function, answer) : null;
    }

    /// <summary>Empties the table.</summary>
    [RelayCommand]
    public void Clear()
    {
        _table = null;
        Rows = [];
        ErrorKey = null;
        Graph.Clear();
    }
}
