// This Source Code Form is subject to the terms of the MIT License.
// If a copy of the MIT was not distributed with this file, You can obtain one at https://opensource.org/licenses/MIT.
// Copyright (C) Barbatos Labs | Pham The Hung and Barbatos.Pallas Contributors.
// All Rights Reserved.

using System.Collections.Immutable;
using Barbatos.Pallas.Engine;
using Barbatos.Pallas.Spreadsheet;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

namespace Barbatos.Pallas.Presentation;

/// <summary>
/// One value of a row as the screen shows it: what the display shows, or the error its calculation ended in.
/// </summary>
/// <param name="Text">What the display shows, or nothing when the calculation failed.</param>
/// <param name="ErrorKey">The localization key of its error, or <see langword="null"/>.</param>
/// <remarks>
/// A value whose calculation failed shows its error where the value would be, as a cell of the sheet does (assumption
/// U34). Until 25 Sep 2026 it showed nothing, which does not say that anything went wrong.
/// </remarks>
public sealed record TableCell(string Text, string? ErrorKey)
{
    /// <summary>Shows a calculation.</summary>
    /// <param name="calculation">The calculation.</param>
    /// <returns>What the screen shows of it.</returns>
    internal static TableCell Of(Calculation calculation) =>
        new(calculation.Display.Text, calculation.Error is null ? null : "error." + calculation.Error.Value.Kind);
}

/// <summary>
/// One row of a table as the screen shows it: x, and f(x) and g(x) where the table holds them.
/// </summary>
/// <param name="X">The value of x.</param>
/// <param name="F">f(x), or <see langword="null"/> when the table holds only g(x).</param>
/// <param name="G">g(x), or <see langword="null"/> when the table holds only f(x).</param>
public sealed record TableLine(TableCell X, TableCell? F, TableCell? G)
{
    /// <summary>Shows a row of a table.</summary>
    /// <param name="row">The row.</param>
    /// <returns>What the screen shows of it.</returns>
    internal static TableLine Of(TableRow row) =>
        new(TableCell.Of(row.X), row.F is null ? null : TableCell.Of(row.F), row.G is null ? null : TableCell.Of(row.G));
}

/// <summary>
/// The Table screen (manual pp. 107-111): f(x) and g(x) over a range of x, row by row.
/// </summary>
/// <remarks>
/// The functions are defined in the session, as they are everywhere else in the calculator, and the table is
/// generated by the Spreadsheet package; the screen holds the range and what came out. The graph
/// (<see cref="TableGraphViewModel"/>) is a second view of the same table, drawn again whenever the table changes.
/// </remarks>
public sealed partial class TableViewModel : ObservableObject
{
    private readonly CalculatorSession _session;
    private readonly SessionWork _work;
    private NumberTable? _table;

    /// <summary>Creates the screen over a session.</summary>
    /// <param name="session">The session the table is generated from.</param>
    /// <param name="work">The session's work, shared by its screens; <see langword="null"/> to calculate where asked.</param>
    /// <exception cref="ArgumentNullException"><paramref name="session"/> is <see langword="null"/>.</exception>
    public TableViewModel(CalculatorSession session, SessionWork? work = null)
    {
        ArgumentNullException.ThrowIfNull(session);
        _session = session;
        _work = work ?? SessionWork.Immediate;
        Range = new ValueGridViewModel(session, 1, 3);
        Range[0, 0].Text = "1";
        Range[0, 1].Text = "5";
        Range[0, 2].Text = "1";
        Graph = new TableGraphViewModel(session);
    }

    /// <summary>Gets the kinds of table there are: f(x) alone, or f(x) and g(x) (p. 107).</summary>
    public ImmutableArray<TableType> Types { get; } = [.. Enum.GetValues<TableType>()];

    /// <summary>Gets the start, the end and the step of x.</summary>
    public ValueGridViewModel Range { get; }

    /// <summary>Gets the graph of the table: its functions over its rows.</summary>
    public TableGraphViewModel Graph { get; }

    /// <summary>Gets or sets whether the screen shows the graph of the table rather than its rows.</summary>
    [ObservableProperty]
    private bool _isGraphShown;

    /// <summary>Gets or sets which functions the table holds.</summary>
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(RowLimit))]
    private TableType _type = TableType.FunctionsFAndG;

    /// <summary>Gets or sets f(x), as Canonical Linear Syntax.</summary>
    [ObservableProperty]
    private string _functionF = "x²";

    /// <summary>Gets or sets g(x), as Canonical Linear Syntax; only used when the table holds both.</summary>
    [ObservableProperty]
    private string _functionG = "x+1";

    /// <summary>Gets the rows of the table.</summary>
    [ObservableProperty]
    private ImmutableArray<TableLine> _rows = [];

    /// <summary>Gets the localization key of the error, or <see langword="null"/>.</summary>
    [ObservableProperty]
    private string? _errorKey;

    /// <summary>Gets how many rows this kind of table may have in this profile (p. 107).</summary>
    public int RowLimit => NumberTable.RowLimit(Type, _session.Profile);

    /// <summary>Defines the functions and generates the table.</summary>
    /// <remarks>
    /// A work of the session: every row is two calculations of what the user wrote, and a table of integrals held the
    /// window for seconds when it was generated on the window's thread.
    /// </remarks>
    [RelayCommand]
    public void Generate()
    {
        ErrorKey = null;
        Rows = [];
        _table = null;
        Graph.Clear();

        TableType type = Type;
        string f = FunctionF;
        string g = FunctionG;
        Value start = Range[0, 0].Value;
        Value end = Range[0, 1].Value;
        Value step = Range[0, 2].Value;
        _work.Start(token => Generated(type, f, g, start, end, step, token), Show);
    }

    /// <summary>Changes the x of one row and calculates that row again (p. 110), as a work of the session.</summary>
    /// <param name="row">The row, counted from 0.</param>
    /// <param name="x">What x is now.</param>
    /// <returns><see langword="true"/> when there is such a row.</returns>
    public bool SetX(int row, Value x)
    {
        NumberTable? table = _table;
        if (table is null || row < 0 || row >= table.Rows.Count)
        {
            return false;
        }

        _work.Start(
            token =>
            {
                table.SetX(row, x, token);
                return table;
            },
            Refresh);
        return true;
    }

    /// <summary>Removes one row of the table (p. 110).</summary>
    /// <param name="row">The row, counted from 0.</param>
    /// <returns><see langword="true"/> when there was such a row.</returns>
    public bool RemoveRow(int row)
    {
        if (_table is not { } table || row < 0 || row >= table.Rows.Count)
        {
            return false;
        }

        table.RemoveRow(row);
        Refresh(table);
        return true;
    }

    /// <summary>Checks an answer against what the table holds (Verify, p. 111).</summary>
    /// <param name="row">The row, counted from 0.</param>
    /// <param name="function">Which function.</param>
    /// <param name="answer">The answer to check.</param>
    /// <returns>Whether it is right, or <see langword="null"/> when there is nothing to check it against.</returns>
    public bool? Verify(int row, TableFunction function, string answer)
    {
        return _table is { } table && row >= 0 && row < table.Rows.Count ? table.Verify(row, function, answer) : null;
    }

    /// <summary>Empties the table.</summary>
    [RelayCommand]
    public void Clear()
    {
        _table = null;
        Rows = [];
        ErrorKey = null;
        Graph.Clear();
    }

    /// <summary>Defines the functions and generates the table, on the session: an error of a definition, or the table.</summary>
    private (CalcError? Fault, NumberTable? Table) Generated(TableType type, string f, string g, Value start, Value end, Value step, CancellationToken token)
    {
        CalcError? fault = type is TableType.FunctionG ? null : _session.Define(DefinedFunction.F, f);
        fault ??= type is TableType.FunctionF ? null : _session.Define(DefinedFunction.G, g);
        return fault is null ? (null, NumberTable.Generate(_session, type, start, end, step, token)) : (fault, null);
    }

    private void Show((CalcError? Fault, NumberTable? Table) generated)
    {
        NumberTable? table = generated.Table;
        if (table is null)
        {
            ErrorKey = "error." + generated.Fault!.Value.Kind;
            return;
        }

        Show(table);
    }

    private void Show(NumberTable table)
    {
        _table = table;
        ErrorKey = table.Error is { } error ? "error." + error.Kind : null;
        Rows = [.. table.Rows.Select(TableLine.Of)];
        Graph.Show(table);
    }

    private void Refresh(NumberTable table)
    {
        // A table cleared or generated again while one of its rows was being calculated is no longer on the screen.
        if (table == _table)
        {
            Rows = [.. table.Rows.Select(TableLine.Of)];
            Graph.Show(table);
        }
    }
}
